version: "3.2"

services:
  web:
    image: nginx:alpine
    restart: always
    ports:
        - "8080:80"
    volumes:
        - ./app:/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lemp
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app

    depends_on:
      - db
    networks:
      - lemp

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secrect
      MYSQL_DATABASE: lemp-db
      MYSQL_USER: lemp-user
      MYSQL_PASSWORD: lemp-pass
    ports:
      - 3306:3306
    networks:
      - lemp
    volumes:
      - ./datadir:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secrect
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    volumes:
      - /sessions
    networks:
      - lemp

networks:
  lemp: