version: "3.2"

services:
  web:
    image: nginx:alpine
    ports:
        - "8080:80"
    volumes:
        - ./app:/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lemp
    depends_on:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./app:/app
    networks:
      - lemp

networks:
  lemp:

    
