version: "3.2"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
        - "8080:80"
    volumes:
        - ./app:/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lemp
    depends_on:
      - php

  php:
    image: patunalu/php-fpm:latest
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks:
      - lemp

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lemp-db
      MYSQL_USER: lemp-user
      MYSQL_PASSWORD: lemp-pass
    networks:
      - lemp
    volumes:
      - ./datadir:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:80
    volumes:
      - /sessions
    networks:
      - lemp

networks:
  lemp: